---
- name: i want to deploy ravi java war file into webapps  
  get_url:
   url: https://sai19.jfrog.io/ui/repos/tree/General/sai22/raviLogin-1.0.war
   dest: /usr/share/tomcat/webapps/raviLogin.war
   force_basic_auth: yes